### ISSUE TITLE
Templates directory not read

### ISSUE THREAD

**Issue by vvevans** [networktocode/ntc-templates#1056]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING

```
??? - arista_eos
```

##### SAMPLE COMMAND OUTPUT

```
result_textfsm = connection.send_command(
    "show version",
    use_textfsm=True,
)
```

##### SUMMARY
Getting a python traceback:

`IsADirectoryError: [Errno 21] Is a directory:` - which then points to the ntc_templates/templates dir

Attempting to use auto template selection to format my data from a netmiko "show version" session to structured data

##### STEPS TO REPRODUCE
Python script that establishes Netmiko connect session to an arista eos device. Enters enable mode, issues "show version" command and should print output.

I've used both the python pip method and the github / poetry method to install ntc_templates, both of which seem to work fine; the package is installed. My python script has no reference to it other than what is shown above (following a course guidelines); seems something should be imported, but not so in the lab.
Running script throws traceback at  "result_textfsm = connection.send_command(" line

##### EXPECTED RESULTS
Script runs and returns printout of both my raw / unstructured data, followed by the structured "TextFSM" output.

##### ACTUAL RESULTS

```
(venv) ┌─[vve1505@pop-vm]─[~/Code/PacketCoders/netmiko-course]
└──╼ $python connect_mock.py 
Traceback (most recent call last):
  File "/home/vve1505/Code/PacketCoders/netmiko-course/connect_mock.py", line 25, in <module>
    result_textfsm = connection.send_command(
  File "/home/vve1505/Code/venv/lib/python3.9/site-packages/netmiko/utilities.py", line 500, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/vve1505/Code/venv/lib/python3.9/site-packages/netmiko/base_connection.py", line 1550, in send_command
    structured_output = get_structured_data(
  File "/home/vve1505/Code/venv/lib/python3.9/site-packages/netmiko/utilities.py", line 344, in get_structured_data
    template_dir = get_template_dir()
  File "/home/vve1505/Code/venv/lib/python3.9/site-packages/netmiko/utilities.py", line 281, in get_template_dir
    with importresources_path(
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1055, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/vve1505/Code/venv/lib/python3.9/site-packages/ntc_templates/templates'

```

**Comment by rce717** [comment]
I'm having the same issue using junos, cisco and Cisco XR templates.

**Comment by jmcgill298** [comment]
This seems to be an issue with netmiko accessing the correct path. I would make sure and follow their docs and report any issues with netmiko back to them. Is there a reason to believe there is an issue with this project?

**Comment by itdependsnetworks** [comment]
no response, closing
