### ISSUE TITLE
Problem with parsing ASA ACL

### ISSUE THREAD

**Issue by pergamen** [networktocode/ntc-templates#287]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
cisco_asa_show_access-list.template
```

##### SAMPLE COMMAND OUTPUT

```
extfsm.TextFSMError: Error: "Did not match any rules". Rule Line: 68. Input Line: access-list out40-if line 14 extended permit icmp any4 any4 time-exceeded log informational interval 300 (hitcnt=3085438) 0x19b0643c .


```

##### SUMMARY

I have wite python script with netmiko module

##### STEPS TO REPRODUCE

```

import netmiko
import warnings
import sys

# main function
if __name__ == '__main__':
     
     warnings.simplefilter("ignore", DeprecationWarning)
     sys.path.append('d:\\appl\\Reports')
     from devices_info import device_asa
     
     address="9.148.2.23"

     connection=netmiko.ConnectHandler( ip = address,
                                        device_type="cisco_asa",
                                        username = device_asa["username"],
                                        password = device_asa["password"],
                                        secret = device_asa["password"]
                                        )

     result = connection.find_prompt()
    
     
     result = connection.send_command("show access-list out40-if", use_textfsm=True)
     print(result)
     connection.disconnect()

```
Original access list:
```
access-list out40-if remark NT00004C12;************ Firewall Filter block Private IP address**************
access-list out40-if extended deny ip any 192.168.0.0 255.255.0.0
access-list out40-if extended deny ip any 127.0.0.0 255.0.0.0
access-list out40-if extended deny ip any 172.16.0.0 255.240.0.0
access-list out40-if extended deny ip any host 255.255.255.255
access-list out40-if extended deny ip any host 0.0.0.0
access-list out40-if extended deny ip 192.168.0.0 255.255.0.0 any
access-list out40-if extended deny ip 127.0.0.0 255.0.0.0 any
access-list out40-if extended deny ip 10.0.0.0 255.0.0.0 any
access-list out40-if extended deny ip 172.16.0.0 255.240.0.0 any
access-list out40-if extended deny ip host 255.255.255.255 any
access-list out40-if extended deny ip host 0.0.0.0 any
access-list out40-if remark NT00004C16;************ Allow ICMP *************
access-list out40-if extended permit icmp any4 any4 time-exceeded log
access-list out40-if extended permit icmp any4 any4 unreachable log
access-list out40-if extended permit icmp any4 any4 echo log
access-list out40-if extended permit icmp any4 any4 echo-reply log
access-list out40-if extended permit icmp any4 9.148.0.0 255.255.0.0 echo
access-list out40-if extended permit icmp any4 9.148.0.0 255.255.0.0 echo-reply
access-list out40-if extended permit icmp any4 9.148.0.0 255.255.0.0 unreachable
access-list out40-if extended permit icmp any4 9.148.0.0 255.255.0.0 time-exceeded
access-list out40-if extended permit icmp any4 9.147.0.0 255.255.0.0 echo-reply
access-list out40-if extended permit icmp any4 9.147.0.0 255.255.0.0 echo
access-list out40-if extended permit icmp any4 9.147.0.0 255.255.0.0 unreachable
access-list out40-if extended permit icmp any4 9.151.0.0 255.255.0.0 echo-reply
access-list out40-if extended permit icmp any4 9.147.0.0 255.255.0.0 time-exceeded
access-list out40-if extended permit icmp any4 9.151.0.0 255.255.0.0 echo
access-list out40-if extended permit icmp any4 9.151.0.0 255.255.0.0 unreachable
access-list out40-if extended permit icmp any4 9.151.0.0 255.255.0.0 time-exceeded
access-list out40-if extended deny icmp any any
access-list out40-if remark NT00004C0E; ************ Firewall Appl Filter block NetBios and SMTP **************
access-list out40-if extended deny udp any any eq snmp
access-list out40-if extended deny tcp any any eq 445
access-list out40-if extended deny tcp any any eq netbios-ssn
access-list out40-if extended deny tcp any any eq 135
access-list out40-if remark ************ Deny all ********************
access-list out40-if extended deny ip any any
```

```yaml

```

##### ACTUAL RESULTS

```
sers\pergamen\PycharmProjects\Network\venv\Scripts\python.exe D:/appl/appl/Networkaccess/ssh/netmiko/Cisco-ASA--netmiko-showver.py
Traceback (most recent call last):
  File "D:/appl/appl/Networkaccess/ssh/netmiko/Cisco-ASA--netmiko-showver.py", line 32, in <module>
    result = connection.send_command("show access-list out40-if", use_textfsm=True)
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\netmiko\cisco\cisco_asa_ssh.py", line 60, in send_command
    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\netmiko\base_connection.py", line 1194, in send_command
    command=command_string.strip())
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\netmiko\utilities.py", line 239, in get_structured_data
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\netmiko\_textfsm\_clitable.py", line 261, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\netmiko\_textfsm\_clitable.py", line 291, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\pergamen\PycharmProjects\Network\venv\lib\site-packages\textfsm.py", line 986, in _Operations
    % (rule.new_state, rule.line_num, line))
textfsm.TextFSMError: Error: "Did not match any rules". Rule Line: 68. Input Line: access-list out40-if line 14 extended permit icmp any4 any4 time-exceeded log informational interval 300 (hitcnt=3085438) 0x19b0643c .

Process finished with exit code 1

```

**Comment by Jaydubya35** [comment]
You're running a `show running-config access-list` command through the `show access-list` parser. Since your output is missing line numbers, hitcounts and the hash it doesn't match.

**Comment by pergamen** [comment]
@Jaydubya35 
Hello thank you for your response 

On the python script I have use `show access-list` 
`result = connection.send_command("show access-list out40-if", use_textfsm=True)`

The access list that I have show it is from Cisco Configuration
However I provide also result of Cisco  `show access-list` from cli
```
5555xhab1cr11# show access-list out40-if
access-list out40-if; 34 elements; name hash: 0x290cd95e
access-list out40-if line 1 remark NT00004C12;************ Firewall Filter block Private IP address**************
access-list out40-if line 2 extended deny ip any 192.168.0.0 255.255.0.0 (hitcnt=0) 0x8b5f6522
access-list out40-if line 3 extended deny ip any 127.0.0.0 255.0.0.0 (hitcnt=0) 0x9738046f
access-list out40-if line 4 extended deny ip any 172.16.0.0 255.240.0.0 (hitcnt=0) 0xa20c7320
access-list out40-if line 5 extended deny ip any host 255.255.255.255 (hitcnt=0) 0x12de5fec
access-list out40-if line 6 extended deny ip any host 0.0.0.0 (hitcnt=0) 0xddd71b9f
access-list out40-if line 7 extended deny ip 192.168.0.0 255.255.0.0 any (hitcnt=0) 0x6277827a
access-list out40-if line 8 extended deny ip 127.0.0.0 255.0.0.0 any (hitcnt=0) 0x4bcf1582
access-list out40-if line 9 extended deny ip 10.0.0.0 255.0.0.0 any (hitcnt=374) 0x7a65a944
access-list out40-if line 10 extended deny ip 172.16.0.0 255.240.0.0 any (hitcnt=0) 0x4a94ea47
access-list out40-if line 11 extended deny ip host 255.255.255.255 any (hitcnt=0) 0xb05f9878
access-list out40-if line 12 extended deny ip host 0.0.0.0 any (hitcnt=0) 0x2c39e58b
access-list out40-if line 13 remark NT00004C16;************ Allow ICMP *************
access-list out40-if line 14 extended permit icmp any any time-exceeded log informational interval 300 (hitcnt=31778) 0x6c633843
access-list out40-if line 15 extended permit icmp any4 any4 time-exceeded log informational interval 300 (hitcnt=0) 0x19b0643c
access-list out40-if line 16 extended permit icmp any4 any4 unreachable log informational interval 300 (hitcnt=1902659) 0x5e72d761
access-list out40-if line 17 extended permit icmp any4 any4 echo log informational interval 300 (hitcnt=0) 0x2405f42c
access-list out40-if line 18 extended permit icmp any4 any4 echo-reply log informational interval 300 (hitcnt=572136) 0x95dca5e7
access-list out40-if line 19 extended permit icmp any4 9.148.0.0 255.255.0.0 echo (hitcnt=0) 0x735d2ad8
access-list out40-if line 20 extended permit icmp any4 9.148.0.0 255.255.0.0 echo-reply (hitcnt=0) 0x4b1cc532
access-list out40-if line 21 extended permit icmp any4 9.148.0.0 255.255.0.0 unreachable (hitcnt=0) 0x3111e9c0
access-list out40-if line 22 extended permit icmp any4 9.148.0.0 255.255.0.0 time-exceeded (hitcnt=0) 0x7a963265
access-list out40-if line 23 extended permit icmp any4 9.147.0.0 255.255.0.0 echo-reply (hitcnt=0) 0x07bfbf99
access-list out40-if line 24 extended permit icmp any4 9.147.0.0 255.255.0.0 echo (hitcnt=0) 0x99e30c47
access-list out40-if line 25 extended permit icmp any4 9.147.0.0 255.255.0.0 unreachable (hitcnt=0) 0x91a15afa
access-list out40-if line 26 extended permit icmp any4 9.151.0.0 255.255.0.0 echo-reply (hitcnt=0) 0xfb31202c
access-list out40-if line 27 extended permit icmp any4 9.147.0.0 255.255.0.0 time-exceeded (hitcnt=0) 0x2bc95316
access-list out40-if line 28 extended permit icmp any4 9.151.0.0 255.255.0.0 echo (hitcnt=0) 0x0f3edcdd
access-list out40-if line 29 extended permit icmp any4 9.151.0.0 255.255.0.0 unreachable (hitcnt=0) 0x7887741b
access-list out40-if line 30 extended permit icmp any4 9.151.0.0 255.255.0.0 time-exceeded (hitcnt=0) 0x480bef5c
access-list out40-if line 31 extended deny icmp any any (hitcnt=3) 0xff7fd0ca
access-list out40-if line 32 remark NT00004C0E; ************ Firewall Appl Filter block NetBios and SMTP **************
access-list out40-if line 33 extended deny udp any any eq snmp (hitcnt=0) 0xe2104da0
access-list out40-if line 34 extended deny tcp any any eq 445 (hitcnt=0) 0x324daac1
access-list out40-if line 35 extended deny tcp any any eq netbios-ssn (hitcnt=0) 0x479e1d4e
access-list out40-if line 36 extended deny tcp any any eq 135 (hitcnt=0) 0x9a6a2095
access-list out40-if line 37 remark ************ Deny all ********************
access-list out40-if line 38 extended deny ip any any (hitcnt=11492793) 0xf4f39374
5555xhab1cr11#
```

**Comment by Jaydubya35** [comment]
@pergamen, thanks for the output from the ASA. I can see that it is failing to pick up on `time-exceeded` in that line. It looks like the template was not written to accept icmp types yet and that is what it is failing on.

Until the template can be fixed, you can always group your icmp-types into an object-group like so:

```
object-group icmp-type icmp-types-group
 icmp-object time-exceeded
 icmp-object unreachable
 icmp-object echo
 icmp-object echo-reply

access-list out40-if extended permit icmp any4 any4 object-group icmp-types-group
```

**Comment by pergamen** [comment]
@Jaydubya35 
Thank yo very much for you quick answer

Your recommendation is help. 

Hover ever is it possible  during process to resolve previous problem look 
also on the on additional bugs:

Bug description:

When you use on python script " show access-list "  command ( without 
specific access list name)  it also failed on the system ACL cashed
 
5525Xhab1cr01# show access-list
access-list cached ACL log flows: total 12, denied 12 (deny-flow-max 4096)
            alert-interval 300
........

Python script failed on this line that contain "access-list cached ACL log 
flows ": 


Error message :

Traceback (most recent call last):
  File 
"D:\appl\appl\Networkaccess\ssh\netmiko\Cisco-ASA--netmiko-showver.py", 
line 33, in <module>
    result = connection.send_command("show access-list", use_textfsm=True)
  File "D:\Python27\lib\site-packages\netmiko\cisco\cisco_asa_ssh.py", 
line 60, in send_command
    output = super(CiscoAsaSSH, self).send_command(*args, **kwargs)
  File "D:\Python27\lib\site-packages\netmiko\base_connection.py", line 
1194, in send_command
    command=command_string.strip())
  File "D:\Python27\lib\site-packages\netmiko\utilities.py", line 239, in 
get_structured_data
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "D:\Python27\lib\site-packages\netmiko\_textfsm\_clitable.py", line 
261, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, 
template_file=template_files[0])
  File "D:\Python27\lib\site-packages\netmiko\_textfsm\_clitable.py", line 
291, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "D:\Python27\lib\site-packages\textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "D:\Python27\lib\site-packages\textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "D:\Python27\lib\site-packages\textfsm.py", line 986, in 
_Operations
    % (rule.new_state, rule.line_num, line))
TextFSMError: Error: "Did not match any rules". Rule Line: 68. Input Line: 
access-list cached ACL log flows: total 210, denied 143 (deny-flow-max 
4096).
>>> 



Thank you very much , I am very appreciate your help.

Best regards,

Victor Pergament
Team Leader :  Networking ,Voice , Video ,Data and Security

Phone: +972-448296367 | Mobile: +972-54-6976367

**Comment by FragmentedPacket** [comment]
@Jaydubya35 I see you have some work on this. Did you ever submit PR for fix?

**Comment by Jaydubya35** [comment]
Oh, sorry I forgot the colon on the auto close syntax. Yes, it got fixed in this PR: https://github.com/networktocode/ntc-templates/pull/313

**Comment by FragmentedPacket** [comment]
No problem! Thanks for updating us and I will close this out
