### ISSUE TITLE
nxos_show_interface_status_template error

### ISSUE THREAD

**Issue by joefodor** [networktocode/ntc-templates#420]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
Value PORT (\S+)
Value NAME (.*?)
Value STATUS (\S+)
Value VLAN (\d+|routed|trunk)
Value DUPLEX (\S+)
Value SPEED (\d+|auto)
Value TYPE (.+?)

Start
  ^[Pp]ort\s+[Nn]ame\s+[Ss]tatus\s+[Vv]lan\s+[Dd]uplex\s+[Ss]peed\s+[Tt]ype\s*$$ -> INTFS
  ^-+\s*$$
  ^$$
  ^.*$$ -> Error

INTFS
  ^${PORT}\s+${NAME}\s+${STATUS}\s+${VLAN}\s+${DUPLEX}\s+${SPEED}\s+${TYPE}\s*$$ -> Record
  ^-+\s*$$
  ^$$
  ^.*$$ -> Error
```

##### SAMPLE COMMAND OUTPUT

```
N7K-TEST# show interface status 

--------------------------------------------------------------------------------
Port             Name            Status    Vlan      Duplex  Speed   Type
--------------------------------------------------------------------------------
mgmt0            --              connected routed    full    a-100   --         
Eth1/1           --              sfpAbsent routed    auto    auto    --         
Eth1/2           --              sfpAbsent routed    auto    auto    --         
Eth1/7           TO SW01  connected routed    full    a-1000  1000base-LH
Eth1/8           TO SW02  notconnec routed    auto    auto    1000base-LH
Eth1/11          TO RTR01  connected routed    full    a-1000  1000base-T 
Eth1/12          --              disabled  routed    auto    auto    1000base-SX
Eth1/13          --              disabled  routed    auto    auto    1000base-SX
Eth1/14          --              notconnec 23        auto    auto    1000base-T 
Eth1/15          --              sfpAbsent routed    auto    auto    --         
Eth1/16          --              sfpAbsent routed    auto    auto    --         
```

##### SUMMARY

Getting a traceback that looks like its failing at the top of the output of the show interface status command. I know my NTC setup is correct cause I ran cisco_nxos_show_interface_brief.template with no problem. 

##### STEPS TO REPRODUCE

```yaml
    - name: show interface status
      ntc_show_command:
        connection: ssh
        template_dir: "/Users/fodorj/Documents/git/nxos_facts/files"
        platform: cisco_nxos
        command: 'show interface status'
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
      register: status
      delegate_to: localhost
      check_mode: false
```

##### EXPECTED RESULTS

Get the output of show interface status in json
##### ACTUAL RESULTS

error out on first line interface

```
task path: /Users/fodorj/Documents/git/nxos_facts/gather_port_info.yml:6
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10>) id=default to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10> for vault_id=default
Decrypt successful with secret=<ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10> and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10>) id=default to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10> for vault_id=default
Decrypt successful with secret=<ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10> and vault_id=default
Found a vault_id (default) in the vaulttext
We have a secret associated with vault id (default), will try to use to decrypt None
Trying to use vault secret=(<ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10>) id=default to decrypt None
Trying secret <ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10> for vault_id=default
Decrypt successful with secret=<ansible.parsing.vault.PromptVaultSecret object at 0x10211ec10> and vault_id=default
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: fodorj
<localhost> EXEC /bin/sh -c 'echo ~fodorj && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841 `" && echo ansible-tmp-1560187103.81-208276021290841="` echo /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841 `" ) && sleep 0'
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/__init__.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/_collections_compat.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/validation.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/sys_info.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/text/__init__.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/_utils.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/process.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/text/formatters.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/text/converters.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/parameters.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/file.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/_json_compat.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/common/collections.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/distro/__init__.py
Using module_utils file /Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/ansible/module_utils/distro/_distro.py
Using module file /Users/fodorj/Documents/git/nxos_facts/library/ntc_show_command.py
<localhost> PUT /Users/fodorj/.ansible/tmp/ansible-local-41775k1o9__/tmp_H5QSU TO /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/ /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/fodorj/miniconda2/envs/ansible2.8/bin/python /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py", line 114, in <module>
    _ansiballz_main()
  File "/Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py", line 511, in <module>
  File "/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py", line 498, in main
  File "/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py", line 316, in parse_raw_output
  File "/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py", line 292, in get_structured_data
  File "/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/clitable.py", line 277, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/clitable.py", line 310, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/textfsm.py", line 989, in _Operations
    % (rule.line_num, line))
textfsm.TextFSMError: State Error raised. Rule Line: 19. Input Line: Eth1/7           TO SW01-Bldg56  connected routed    full    a-1000  1000base-LH

fatal: [n7k-test.com -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/fodorj/.ansible/tmp/ansible-tmp-1560187103.81-208276021290841/AnsiballZ_ntc_show_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py\", line 511, in <module>\n  File \"/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py\", line 498, in main\n  File \"/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py\", line 316, in parse_raw_output\n  File \"/var/folders/mf/5_fm8pgx593_82qdqb1wkrd4jrn9tj/T/ansible_ntc_show_command_payload_WWAiSo/__main__.py\", line 292, in get_structured_data\n  File \"/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/clitable.py\", line 277, in ParseCmd\n    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])\n  File \"/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/clitable.py\", line 310, in _ParseCmdItem\n    for record in fsm.ParseText(cmd_input):\n  File \"/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/textfsm.py\", line 885, in ParseText\n    self._CheckLine(line)\n  File \"/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/textfsm.py\", line 908, in _CheckLine\n    if self._Operations(rule, line):\n  File \"/Users/fodorj/miniconda2/envs/ansible2.8/lib/python2.7/site-packages/textfsm.py\", line 989, in _Operations\n    % (rule.line_num, line))\ntextfsm.TextFSMError: State Error raised. Rule Line: 19. Input Line: Eth1/7           TO SW01-Bldg56  connected routed    full    a-1000  1000base-LH\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}


```

**Comment by FragmentedPacket** [comment]
@joefodor It doesn't appear that you're using the latest template from the repo. If you pull the latest, that should resolve your issue.

**Comment by FragmentedPacket** [comment]
I'm going to go ahead and close this issue. If the issue still occurs with using the latest ntc-templates please re-open or create a new issue.
