### ISSUE TITLE
cisco_ios_show_ip_eigrp_topology.template does not deal with redistributed routes.

### ISSUE THREAD

**Issue by thomasbridge74** [networktocode/ntc-templates#459]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING
```
Value Filldown PROCESS_ID (\d+)
Value Filldown ROUTER_ID (\d+\.\d+\.\d+\.\d+)
Value Required CODE (\S+)
Value ROUTE (\d+\.\d+\.\d+\.\d+)
Value MASK (\d+)
Value SUCCESSORS (\d+)
Value FD (\d+)
Value TAG (\d+)
Value List ADV_ROUTER (\d+\.\d+\.\d+\.\d+|\w+)
Value List OUT_INTERFACE (\S+)

Start
  # Captures Process ID and Router ID
  ^.+AS\(${PROCESS_ID}\)/ID\(${ROUTER_ID}\)
  # Skips over the code line that explains what each code means
  ^Codes:
  # Skips over the definitions for the codes
  ^\s+\S+\s+-\s+
  # Matches a route and captures if ${TAG} is use for the route and then moves to Gateway section
  ^${CODE}\s+${ROUTE}/${MASK},\s+${SUCCESSORS}\s+successors,\s+FD\s+is\s+${FD},\s+tag\s+is\s+${TAG} -> Gateway
  # Matches a route and captures it and then moves to Gateway section
  ^${CODE}\s+${ROUTE}/${MASK},\s+${SUCCESSORS}\s+successors,\s+FD\s+is\s+${FD} -> Gateway
  # If it doesn't match anything above, this just acknowledges a new line
  ^\s*$$
  # This will throw an error if there are no matches
  ^. -> Error

Gateway
  # This captures the advertising router and outgoing interface
  ^\s+via\s+${ADV_ROUTER},\s+${OUT_INTERFACE}
  # This will not capture anything but if it encounters another route, it will continue and record what it already captured
  ^\S+\s+(?:\d+(?:\.|)){4}/\d+,\s+\d+\s+successors -> Continue.Record
  # These are the same as above and capture the next set of routes
  ^${CODE}\s+${ROUTE}/${MASK},\s+${SUCCESSORS}\s+successors,\s+FD\s+is\s+${FD},\s+tag\s+is\s+${TAG}
  ^${CODE}\s+${ROUTE}/${MASK},\s+${SUCCESSORS}\s+successors,\s+FD\s+is\s+${FD}
  # If it encounters another AS/Router ID it will continue and record what it just captured
  ^.+AS\(\d+\)/ID -> Continue.Record
  # If it encounters it again, it will continue, but clear all captured data other than Filldown Values
  ^.+AS\(\d+\)/ID -> Continue.Clearall
  # It will start the process over again if it encounters a new process ID / router id
  ^.+AS\(${PROCESS_ID}\)/ID\(${ROUTER_ID}\)
  ^Codes: -> Start
  # If it doesn't match anything above, this just acknowledges a new line
  ^\s*$$
  # This will throw an error if there are no matches
  ^. -> Error
```

##### SAMPLE COMMAND OUTPUT
```
IP-EIGRP Topology Table for AS(65000)/ID(10.2.0.1)

Codes: P - Passive, A - Active, U - Update, Q - Query, R - Reply,
       r - reply Status, s - sia Status

P 10.50.20.4/32, 2 successors, FD is 128039168
        via 10.4.0.1, GigabitEthernet1/1
        via 10.4.0.2, GigabitEthernet1/2
P 10.50.21.0/27, 0 successors, FD is Inaccessible, tag is 6508497
        via 10.4.0.1, GigabitEthernet1/1
        via 10.4.0.2, GigabitEthernet1/2
P 10.50.75.0/24, 1 successors, FD is 2816
        via Rstatic
P 10.50.23.92/30, 1 successors, FD is 3840256, tag is 5507497
        via Redistributed
```

##### SUMMARY
The template file for show ip eigrp topology (on Cisco IOS boxes) does not cover all the possible  options.

Specifically it can't cope if the FD is set Inaccessible, or if the route is learned via Redistribution, where the output is "via Rstatic" or "via Redistributed" rather than via an IP address.

##### STEPS TO REPRODUCE

```
# output set to the above 
from ntc_templates.parse import parse_output
eigrp_parsed = parse_output(platform="cisco_ios", command="show ip eigrp top", data=output)

```

##### EXPECTED RESULTS
I expected a parsed object for the output of the command.

##### ACTUAL RESULTS

```
eigrp_parsed = parse_output(platform="cisco_ios", command="show ip eigrp top", data=output)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "c:\users\f1im0jn\workspace\network-scripts\ntc-templates\lib\ntc_templates\parse.py", line 42, in parse_output
    cli_table.ParseCmd(data, attrs)
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\clitable.py", line 277, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\clitable.py", line 310, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\textfsm.py", line 989, in _Operations
    % (rule.line_num, line))
textfsm.TextFSMError: State Error raised. Rule Line: 46. Input Line: P 10.50.21.0/27, 0 successors, FD is Inaccessible, tag is 6508497
```

If I remove the entry with the Inaccessible FD, and rerun I get the error below:

```
eigrp_parsed = parse_output(platform="cisco_ios", command="show ip eigrp top", data=output2)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "c:\users\f1im0jn\workspace\network-scripts\ntc-templates\lib\ntc_templates\parse.py", line 42, in parse_output
    cli_table.ParseCmd(data, attrs)
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\clitable.py", line 277, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\clitable.py", line 310, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\textfsm.py", line 885, in ParseText
    self._CheckLine(line)
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\textfsm.py", line 908, in _CheckLine
    if self._Operations(rule, line):
  File "C:\Users\F1IM0JN\AppData\Roaming\Python\Python35\site-packages\textfsm.py", line 989, in _Operations
    % (rule.line_num, line))
textfsm.TextFSMError: State Error raised. Rule Line: 46. Input Line:         via Rstatic
```

**Comment by thomasbridge74** [comment]
#445  has been submitted with a fix.
