### ISSUE TITLE
arista route template

### ISSUE THREAD

**Issue by nncse** [networktocode/ntc-templates#57]
Hi,

I noticed that there is no arista_eos_show_ip_route.template entry and I tried to create one but unsuccessful. Has anyone done this before and please advise on what I am missing or doing wrong?
When the playbook is run, there are no results. Without the template, doing a "show ip route" shows the routes just not in structured format. Below is the config and the results.

Thanks in advance!

Entry in the index file:
==============
arista_eos_show_ip_route.template, .*, arista_eos, sh[[ow]] i[[p]] ro[[ute]]

arista_eos_show_ip_route.template:
======================
Value Filldown Protocol (\S)
Value Type (\S+)
Value Filldown Network (\d+\.\d+\.\d+\.\d+)
Value Filldown Mask (\d+)
Value Distance (\d+)
Value Metric (\d+)
Value Next_Hop (\d+\.\d+\.\d+\.\d+)
Value Interface (\S+)

Start
  ^${Protocol}\s+${Type}\s+${Network}/${Mask}\s[${Distance}/${Metric}]\svia\s${Next_Hop},\s${Interface} -> Record

EOF

YAML FILE
=======
---
- name: GET ROUTES (EOS)
  hosts: eos
  gather_facts: no
  connection: local
  
  tasks:

    - name: GET ROUTES
      ntc_show_command:
        connection=ssh
        platform=arista_eos
        command='show ip route'
        host={{ inventory_hostname }}
        username={{ username }}
        password={{ password }}
      register: route_eos
      tags: route_eos

    - debug: var=route_eos

RESULTS:
=======
PLAY [AUTO CONFIGURE PORT DESCRIPTIONS (EOS)] **********************************

TASK [GET ROUTES] **************************************************************
ok: [a7124]

TASK [debug] *******************************************************************
ok: [a7124] => {
    "route_eos": {
        "changed": false, 
        "response": [], 
        "response_list": []
    }
}

PLAY RECAP *********************************************************************
a7124                      : ok=2    changed=0    unreachable=0    failed=0

**Comment by sjtarik** [comment]
Please check this wiki on how to parse a multiline [records](https://github.com/google/textfsm/wiki/Code-Lab). This page has a pretty good example on how to parse cisco show ip route as well which should be pretty similar to Arista. I think multi line records and IP pattern in template causing the issues.

**Comment by itdependsnetworks** [comment]
@nncse can you please provide a few examples of the show ip route data from an arista?

**Comment by nncse** [comment]
Thanks itdependnetworks! Below is a snapshot of the routing table from an Arista box.

Codes: C - connected, S - static, K - kernel, 
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
       R - RIP, I - ISIS, A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route 

Gateway of last resort is not set

B E    10.1.31.100/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.1.31.101/32 [200/0] via 192.168.17.5, Ethernet18
 C      10.1.31.102/32 is directly connected, Loopback100
 C      10.1.31.200/32 is directly connected, Loopback10
 B E    10.1.31.254/32 [200/0] via 192.168.17.5, Ethernet18
 C      10.63.255.8/30 is directly connected, Ethernet20
 B E    10.100.22.52/30 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.22.56/30 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.11/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.12/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.15/32 [200/0] via 192.168.17.5, Ethernet18

**Comment by itdependsnetworks** [comment]
Doesn't look too bad. If I get a chance tonight I'll knock it out.

**Comment by itdependsnetworks** [comment]
Let me know if this works for you, if it does I will put in a PR to have it added. 

```Value Filldown PROTOCOL (\S+\s\S+?|\w?)
Value Filldown NETWORK (\d+.\d+.\d+.\d+)
Value Filldown MASK (\d+)
Value DISTANCE (\d+)
Value METRIC (\d+)
Value DIRECT (directly)
Value Required NEXT_HOP (connected|\d+\.\d+\.\d+\.\d+)
Value INTERFACE (\S+)

Start
  ^${PROTOCOL}\s+${NETWORK}/${MASK}\s+\[${DISTANCE}/${METRIC}\](?:.+?)${NEXT_HOP},\s+${INTERFACE}$$ -> Next.Record
  ^${PROTOCOL}\s+${NETWORK}/${MASK}\s+is\s+${Direct}(?:.+?)${NEXT_HOP},\s+${INTERFACE}$$ -> Next.Record
  ^${PROTOCOL}\s+${NETWORK}/${MASK}(?:.+?)${NEXT_HOP},\s+${INTERFACE}$$ -> Next.Record
```

**Comment by nncse** [comment]
Thanks! Just a quick question, even though I did not try to run it yet, should variable { PROTOCOL } be listed as "Value PROTOCOL (\S+) before it can be used?

**Comment by itdependsnetworks** [comment]
oops, a bad copy paste job, updated. (note: you can't have \`\`\` on same line as first line.)

**Comment by nncse** [comment]
Thanks! I tried and still the same results. Also, this is how the index file looks like for the arista eos route template.

arista_eos_show_ip_route.template, .*, arista_eos, sh[[ow]] i[[p]] ro[[ute]]

**Comment by itdependsnetworks** [comment]
Seems to work for me
playbook:
```
  - name: CREATE CONFIG FILE
    hosts: localhost
    gather_facts: no
    connection: local

    tasks:
    - name: SHOW INTERFACES SWITCHPORT
      ntc_show_command:
        connection: offline
        file: '/github/ntc-templates/tests/arista_eos/show_ip_route/arista_eos_show_ip_route.raw'
        platform: 'arista_eos'
        command: 'show ip route'
        template_dir: '/github/ntc-templates/templates/'
      register: ip_route

    - name: debug
      debug:
        var: ip_route
```
result

```
TASK: [SHOW INTERFACES SWITCHPORT] ********************************************
ok: [localhost]

TASK: [debug] *****************************************************************
ok: [localhost] => {
    "var": {
        "ip_route": {
            "changed": false,
            "invocation": {
                "module_args": "",
                "module_name": "ntc_show_command"
            },
            "response": [
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "32",
                    "metric": "0",
                    "network": "10.1.31.100",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "32",
                    "metric": "0",
                    "network": "10.1.31.101",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "directly",
                    "distance": "",
                    "interface": "Loopback100",
                    "mask": "32",
                    "metric": "",
                    "network": "10.1.31.102",
                    "next_hop": "connected",
                    "protocol": "C"
                },
                {
                    "direct": "directly",
                    "distance": "",
                    "interface": "Loopback10",
                    "mask": "32",
                    "metric": "",
                    "network": "10.1.31.200",
                    "next_hop": "connected",
                    "protocol": "C"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "32",
                    "metric": "0",
                    "network": "10.1.31.254",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "directly",
                    "distance": "",
                    "interface": "Ethernet20",
                    "mask": "30",
                    "metric": "",
                    "network": "10.63.255.8",
                    "next_hop": "connected",
                    "protocol": "C"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "30",
                    "metric": "0",
                    "network": "10.100.22.52",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "30",
                    "metric": "0",
                    "network": "10.100.22.56",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "32",
                    "metric": "0",
                    "network": "10.100.233.11",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "32",
                    "metric": "0",
                    "network": "10.100.233.12",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                },
                {
                    "direct": "",
                    "distance": "200",
                    "interface": "Ethernet18",
                    "mask": "32",
                    "metric": "0",
                    "network": "10.100.233.15",
                    "next_hop": "192.168.17.5",
                    "protocol": "B E"
                }
            ],
            "response_list": []
        }
    }
}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

(ansible1.9.2) ken@kcelenza-ubuntu:/github/test-ansible$

```

**Comment by nncse** [comment]
Without this entry on the index file (arista_eos_show_ip_route.template, .*, arista_eos, sh[[ow]] i[[p]] ro[[ute]]), doing a "show ip route" shows the routes just not in structured format. When I put it back in, it only displays...

TASK [GET ROUTES] **************************************************************
ok: [a7124]

TASK [debug] *******************************************************************
ok: [a7124] => {
    "route_eos": {
        "changed": false, 
        "response": [], 
        "response_list": []
    }
}

PLAY RECAP *********************************************************************
a7124                      : ok=2    changed=0    unreachable=0    failed=0

**Comment by itdependsnetworks** [comment]
Can you put your output within blocks of code: e.g. 
\`\`\` 
bunch of code 
...
\`\`\`

I can't make out if that brackets is in your index file or not. It's working for me so I suspect something else. Can you also statically define your `template_dir` directory?

**Comment by nncse** [comment]
TASK [GET ROUTES] **************************************************************
ok: [a7124]

TASK [debug] *******************************************************************
ok: [a7124] => {
    "route_eos": {
        "changed": false, 
        "response": [], 
        "response_list": []
    }
}

PLAY RECAP *********************************************************************
a7124                      : ok=2    changed=0    unreachable=0    failed=0   


And yes, these are brackets in the index file.
arista_eos_show_ip_route.template, .*, arista_eos, sh[[ow]] i[[p]] ro[[ute]]

Here is the config file with the template_dir statically defined.

---
- name: ROUTES (EOS)
  hosts: eos
  gather_facts: no
  connection: local
  
  tasks:

    - name: GET ROUTES
      ntc_show_command:
        connection=ssh
        file='/home/user/ansible-files/ntc-ansible/ntc-templates/templates/arista_eos_show_ip_route.template'
        platform=arista_eos
        command='show ip route'
        host={{ inventory_hostname }}
        username={{ username }}
        password={{ password }}
        template_dir='/home/user/ansible-files/ntc-ansible/ntc-templates/templates'
      register: route_eos
      tags: route_eos

    - debug: var=route_eos

**Comment by itdependsnetworks** [comment]
Please see previous note about formatting. For instance it seems like there is no ident between ntc_show_command and the next line, but I can't tell.

**Comment by nncse** [comment]
```
TASK [GET ROUTES] **************************************************************
ok: [a7124]

TASK [debug] *******************************************************************
ok: [a7124] => {
      "route_eos": {
              "changed": false,
              "response": [],
              "response_list": []
       }
}
```
PLAY RECAP *********************************************************************
a7124 : ok=2 changed=0 unreachable=0 failed=0
```


    name: ROUTES (EOS)
    hosts: eos
    gather_facts: no
    connection: local

    tasks:

        - name: GET ROUTES
          ntc_show_command:
             connection=ssh
             file='/home/user/ansible-files/ntc-ansible/ntc-templates/templates /arista_eos_show_ip_route.template'
             platform=arista_eos
             command='show ip route'
             host={{ inventory_hostname }}
             username={{ username }}
             password={{ password }}
             template_dir='/home/user/ansible-files/ntc-ansible/ntc-templates/templates'
           register: route_eos
           tags: route_eos

         - debug: var=route_eos
```

Entry in the index file
```
arista_eos_show_ip_route.template, .*, arista_eos, sh[[ow]] i[[p]] ro[[ute]]
```

**Comment by itdependsnetworks** [comment]
just guessing here. remove file and quote "arista_eos" 
Can also join slack to communicate: https://networktocode.herokuapp.com/

**Comment by jedelman8** [comment]
@nncse can you try another command like `show vlan` or `show interfaces` ?  

Can you also try putting your new line as the first line in the index file?

**Comment by nncse** [comment]
I did a ```show ip arp``` and it works.

```
TASK [GET ROUTES] **************************************************************
ok: [a7124]

TASK [debug] *******************************************************************
ok: [a7124] => {
    "route_eos": {
        "changed": false, 
        "response": [
            {
                "address": "192.168.17.5", 
                "age": "0", 
                "interface": "Ethernet18", 
                "mac": "24e9.b39d.35fc"
            }, 
            {
                "address": "10.63.255.10", 
                "age": "0", 
                "interface": "Ethernet20", 
                "mac": "001e.4a36.fa10"
            }, 
            {
                "address": "192.168.38.5", 
                "age": "0", 
                "interface": "Ethernet21", 
                "mac": "50c5.8db1.04b0"
            }, 
            {
                "address": "172.28.114.233", 
                "age": "0", 
                "interface": "Ethernet22", 
                "mac": "0022.0c9a.0e41"
            }
        ], 
        "response_list": []
    }
}
```


I put the route template on this first line on the index file and still the same.

**Comment by nncse** [comment]
I tried to change the index entry for eos route and now I am getting traceback errors.
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py", line 443, in <module>
    main()
  File "/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py", line 430, in main
    results['response'] = parse_raw_output(rawtxt, module)
  File "/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py", line 296, in parse_raw_output
    structured_data = get_structured_data(rawoutput, module)
  File "/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py", line 272, in get_structured_data
    cli_table.ParseCmd(rawoutput, attrs)
  File "/usr/local/lib/python2.7/dist-packages/clitable.py", line 241, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/usr/local/lib/python2.7/dist-packages/clitable.py", line 262, in _ParseCmdItem
    fsm = textfsm.TextFSM(template_file)
  File "/usr/local/lib/python2.7/dist-packages/textfsm/textfsm.py", line 546, in __init__
    self._Parse(template)
  File "/usr/local/lib/python2.7/dist-packages/textfsm/textfsm.py", line 647, in _Parse
    while self._ParseFSMState(template):
  File "/usr/local/lib/python2.7/dist-packages/textfsm/textfsm.py", line 778, in _ParseFSMState
    self._line_num)
textfsm.textfsm.TextFSMTemplateError: Missing white space or carat ('^') before rule. Line: 11

fatal: [a7124]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ntc_show_command"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py\", line 443, in <module>\n    main()\n  File \"/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py\", line 430, in main\n    results['response'] = parse_raw_output(rawtxt, module)\n  File \"/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py\", line 296, in parse_raw_output\n    structured_data = get_structured_data(rawoutput, module)\n  File \"/tmp/ansible_V4Zmkt/ansible_module_ntc_show_command.py\", line 272, in get_structured_data\n    cli_table.ParseCmd(rawoutput, attrs)\n  File \"/usr/local/lib/python2.7/dist-packages/clitable.py\", line 241, in ParseCmd\n    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])\n  File \"/usr/local/lib/python2.7/dist-packages/clitable.py\", line 262, in _ParseCmdItem\n    fsm = textfsm.TextFSM(template_file)\n  File \"/usr/local/lib/python2.7/dist-packages/textfsm/textfsm.py\", line 546, in __init__\n    self._Parse(template)\n  File \"/usr/local/lib/python2.7/dist-packages/textfsm/textfsm.py\", line 647, in _Parse\n    while self._ParseFSMState(template):\n  File \"/usr/local/lib/python2.7/dist-packages/textfsm/textfsm.py\", line 778, in _ParseFSMState\n    self._line_num)\ntextfsm.textfsm.TextFSMTemplateError: Missing white space or carat ('^') before rule. Line: 11\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

**Comment by itdependsnetworks** [comment]
can you double check the spelling of the .template file?

**Comment by nncse** [comment]
```
arista_eos_show_ip_route.template
```

**Comment by jedelman8** [comment]
This error is better...can you now how the full contents of the template file?

**Comment by nncse** [comment]
```
Value Filldown Protocol (\S+)
Value Type (\S+)
Value Filldown Network (\d+.\d+.\d+.\d+)
Value Filldown Mask (\d+)
Value Distance (\d+)
Value Metric (\d+)
Value Next_Hop (\d+.\d+.\d+.\d+)
Value Interface (\S+)

Start
^${Protocol}\s+${Type}\s+${Network}/${Mask}\s[${Distance}/${Metric}]\svia\s${Next_Hop},\s${Interface} -> Record

EOF  
```

**Comment by jedelman8** [comment]
You have this

```
Start
^${Protocol}\s+${Type}\s+${Network}/${Mask}\s[${Distance}/${Metric}]\svia\s${Next_Hop},\s${Interface} -> Record
```

Change to this (adding 2 spaces before the `^`):

```
Start
  ^${Protocol}\s+${Type}\s+${Network}/${Mask}\s[${Distance}/${Metric}]\svia\s${Next_Hop},\s${Interface} -> Record
```

**Comment by nncse** [comment]
Thanks Jason! Excuse me for the error, it must be from the copy/paste from my notepad. Now I am back to the previous output which is without the route entries.
```
TASK [GET ROUTES] **************************************************************
ok: [a7124]

TASK [debug] *******************************************************************
ok: [a7124] => {
    "route_eos": {
        "changed": false, 
        "response": [], 
        "response_list": []
    }
}

PLAY RECAP *********************************************************************
a7124                      : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by GGabriele** [comment]
@nncse I think the actual problem was in the raw text format that you posted.
Try this template please (I simply added a `\s+` at the beginning of the regex line):

```
Value Filldown PROTOCOL (\S+\s\S+?|\w?)
Value Filldown NETWORK (\d+.\d+.\d+.\d+)
Value Filldown MASK (\d+)
Value DISTANCE (\d+)
Value METRIC (\d+)
Value DIRECT (directly)
Value Required NEXT_HOP (connected|\d+\.\d+\.\d+\.\d+)
Value INTERFACE (\S+)

Start
  ^\s+${PROTOCOL}\s+${NETWORK}/${MASK}\s+(?:\[${DISTANCE}/${METRIC}\]|is\s+${DIRECT})(?:.+?)${NEXT_HOP},\s+${INTERFACE}$$ -> Next.Record
```

**Comment by nncse** [comment]
Thank you for all the help!!! You guys are awesome! It works now.

**Comment by GGabriele** [comment]
No problem! :)

**Comment by itdependsnetworks** [comment]
@nncse can you please provide an example within a code block? Even doing a view source I can't tell what the spacing actually is. If you could show everything you see from the command line that would be helpful. For instance I see `VRF name: default` as second line on a test box, but not sure if that is always there.

**Comment by nncse** [comment]
Is this what you are referring to?
```
---
- name: ROUTES (EOS)
  hosts: eos
  gather_facts: no
  connection: local

  tasks:

    - name: GET ROUTES
      ntc_show_command:
        connection=ssh
        platform=arista_eos
        command='show ip route'
        host={{ inventory_hostname }}
        username={{ username }}
        password={{ password }}
      register: route_eos
      tags: route_eos

    - debug: var=route_eos
```

**Comment by itdependsnetworks** [comment]
@nncse the raw file. something like: 

```
Codes: C - connected, S - static, K - kernel,
O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
R - RIP, I - ISIS, A B - BGP Aggregate, A O - OSPF Summary,
NG - Nexthop Group Static Route

Gateway of last resort is not set

B E 10.1.31.100/32 [200/0] via 192.168.17.5, Ethernet18
B E 10.1.31.101/32 [200/0] via 192.168.17.5, Ethernet18
C 10.1.31.102/32 is directly connected, Loopback100
C 10.1.31.200/32 is directly connected, Loopback10
B E 10.1.31.254/32 [200/0] via 192.168.17.5, Ethernet18
```
but with the correct spacing. We have tests for each one of these, and my test doesn't match up with your actual output, which was part of the confusion.

**Comment by nncse** [comment]
Ok, here it is.
```
a7124#show ip route
Codes: C - connected, S - static, K - kernel, 
       O - OSPF, IA - OSPF inter area, E1 - OSPF external type 1,
       E2 - OSPF external type 2, N1 - OSPF NSSA external type 1,
       N2 - OSPF NSSA external type2, B I - iBGP, B E - eBGP,
       R - RIP, I - ISIS, A B - BGP Aggregate, A O - OSPF Summary,
       NG - Nexthop Group Static Route 

Gateway of last resort is not set

 B E    10.1.31.100/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.1.31.101/32 [200/0] via 192.168.17.5, Ethernet18
 C      10.1.31.102/32 is directly connected, Loopback100
 C      10.1.31.200/32 is directly connected, Loopback10
 B E    10.1.31.254/32 [200/0] via 192.168.17.5, Ethernet18
 C      10.63.255.8/30 is directly connected, Ethernet20
 B E    10.100.22.52/30 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.22.56/30 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.11/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.12/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.15/32 [200/0] via 192.168.17.5, Ethernet18
 C      10.100.233.32/32 is directly connected, Loopback0
 B E    10.100.233.34/32 [200/0] via 192.168.38.5, Ethernet21
 B E    10.100.233.50/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.64/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.66/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.67/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.68/32 [200/0] via 192.168.17.5, Ethernet18
 B E    10.100.233.192/32 [200/0] via 10.63.255.10, Ethernet20
```

**Comment by itdependsnetworks** [comment]
That worked, thanks!
