### ISSUE TITLE
Unable to parse data by using "cisco_ios_show_ip_route_summary.textfsm"

### ISSUE THREAD

**Issue by angelademo2020** [networktocode/ntc-templates#643]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING
```
cisco_ios_show_ip_route_summary.textfsm
```

##### SAMPLE COMMAND OUTPUT
```
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    vlan_parsed = parse_output(platform="cisco_ios", command="show ip route summary", data=vlan_output)
  File "$PWD/ntc-templates/lib/ntc_templates/parse.py", line 39, in parse_output
    cli_table.ParseCmd(data, attrs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/textfsm/clitable.py", line 282, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/textfsm/clitable.py", line 315, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/textfsm/parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/textfsm/parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/textfsm/parser.py", line 1025, in _Operations
    % (rule.line_num, line))
textfsm.parser.TextFSMError: State Error raised. Rule Line: 33. Input Line: *04:02:16.890 UTC Tue Apr 7 2020
```

##### STEPS TO REPRODUCE

1. generate an text file from ansible
2. with some commands for example:
`show clock` and `show ip route summary`
3. the text file should contains the output of `show clock` and `show ip route summary`
4. parse the text file
5. got Traceback error on `show ip route summary`

```yaml
show ip route summary
```

##### EXPECTED RESULTS

some json parsed by "cisco_ios_show_ip_route_summary.textfsm"
##### ACTUAL RESULTS

```
Traceback error above
```

**Comment by FragmentedPacket** [comment]
Can you please provide the raw output of this command? I assume it's changed somehow and we need to account for it, but want to make sure we're updating the template against real data.

**Comment by delhipnr** [comment]
> Can you please provide the raw output of this command? I assume it's changed somehow and we need to account for it, but want to make sure we're updating the template against real data.


Hi Thank you so much for a quick commitment. Now it is working.

```
PS C:\Users\a0725645> pip install --upgrade ntc_templates
Collecting ntc_templates
  Downloading https://files.pythonhosted.org/packages/5b/04/d0b8155d63e3834cce60d1c6cda350b0204cee0ab1dfe6cc63c8c635772e
/ntc_templates-1.4.1-py3-none-any.whl (227kB)
     |████████████████████████████████| 235kB 115kB/s
Requirement already satisfied, skipping upgrade: textfsm in c:\users\a0725645\appdata\local\programs\python\python37-32\
lib\site-packages (from ntc_templates) (0.4.1)
Requirement already satisfied, skipping upgrade: terminal in c:\users\a0725645\appdata\local\programs\python\python37-32
\lib\site-packages (from ntc_templates) (0.4.0)
Requirement already satisfied, skipping upgrade: colorama in c:\users\a0725645\appdata\roaming\python\python37\site-pack
ages (from terminal->ntc_templates) (0.4.1)
Installing collected packages: ntc-templates
  Found existing installation: ntc-templates 1.4.0
    Uninstalling ntc-templates-1.4.0:
      Successfully uninstalled ntc-templates-1.4.0
Successfully installed ntc-templates-1.4.1
WARNING: You are using pip version 19.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\a0725645> pip show ntc_templates
Name: ntc-templates
Version: 1.4.1
Summary: Package to return structured data from the output of network devices.
Home-page: https://github.com/networktocode/ntc-templates
Author: network.toCode()
Author-email: info@networktocode.com
License: UNKNOWN
Location: c:\users\a0725645\appdata\local\programs\python\python37-32\lib\site-packages
Requires: textfsm, terminal
Required-by:
PS C:\Users\a0725645>


++++++++++++++++++++++++++++++++++++++++++++++++++
from ntc_templates.parse import parse_output
from pprint import pprint

payload = '''
IP routing table name is default (0x0)
IP routing table maximum-paths is 32
Route Source    Networks    Subnets     Replicates  Overhead    Memory (bytes)
connected       0           0           0           0           0
static          0           0           0           0           0
application     0           0           0           0           0
bgp 65190       0           0           0           0           0
  External: 0 Internal: 0 Local: 0
internal        0                                               40
Total           0           0           0           0           40
'''

vlan_parsed = parse_output(platform="cisco_ios", command="sh ip ro sum", data=payload)
pprint(vlan_parsed)

=============== RESTART: C:\Temp\reactsap\ntc_template\ntc.py ===============
[{'memory': '15640',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '5780',
  'replicates': '0',
  'route_source': 'connected',
  'subnets': '85'},
 {'memory': '41768',
  'name': 'default (0x0)',
  'networks': '8',
  'overhead': '15436',
  'replicates': '0',
  'route_source': 'static',
  'subnets': '219'},
 {'memory': '0',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '0',
  'replicates': '0',
  'route_source': 'application',
  'subnets': '0'},
 {'memory': '1234088',
  'name': 'default (0x0)',
  'networks': '58',
  'overhead': '726036',
  'replicates': '0',
  'route_source': 'bgp 65182',
  'subnets': '6649'},
 {'memory': '305084',
  'name': 'default (0x0)',
  'networks': '146',
  'overhead': '',
  'replicates': '',
  'route_source': 'internal',
  'subnets': ''},
 {'memory': '1596580',
  'name': 'default (0x0)',
  'networks': '212',
  'overhead': '747252',
  'replicates': '0',
  'route_source': 'Total',
  'subnets': '6953'}]
>>> 
 RESTART: C:\Users\a0725645\AppData\Local\Programs\Python\Python37-32\dictl.py 
[{'memory': '0',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '0',
  'replicates': '0',
  'route_source': 'connected',
  'subnets': '0'},
 {'memory': '0',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '0',
  'replicates': '0',
  'route_source': 'static',
  'subnets': '0'},
 {'memory': '0',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '0',
  'replicates': '0',
  'route_source': 'application',
  'subnets': '0'},
 {'memory': '0',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '0',
  'replicates': '0',
  'route_source': 'bgp 65190',
  'subnets': '0'},
 {'memory': '40',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '',
  'replicates': '',
  'route_source': 'internal',
  'subnets': ''},
 {'memory': '40',
  'name': 'default (0x0)',
  'networks': '0',
  'overhead': '0',
  'replicates': '0',
  'route_source': 'Total',
  'subnets': '0'}]
>>> 
```

**Comment by FragmentedPacket** [comment]
Thanks for the report!
