### ISSUE TITLE
Beginning of output for cisco_ios "show ip ospf database <lsa-type>" may or may not be a space character

### ISSUE THREAD

**Issue by ariesgeek** [networktocode/ntc-templates#649]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING

```
Value Filldown ROUTER_ID (\d+\.\d+\.\d+\.\d+)
Value Filldown PROCESS_ID (\d+)
Value Filldown AREA (\d+\.\d+\.\d+\.\d+|\d+)
Value Filldown LSA_AGE (\d+)
Value Filldown LSA_OPTIONS (.+)
Value Filldown LSA_TYPE (.+)
Value Filldown LSA_ID (\d+\.\d+\.\d+\.\d+)
Value Filldown LSA_ADV_ROUTER (\d+\.\d+\.\d+\.\d+)
Value Filldown LSA_SEQ_NUMBER (\S+)
Value Filldown LSA_CHECKSUM (\S+)
Value Filldown LSA_LENGTH (\d+)
Value Filldown LSA_NUM_LINKS (\d+)
Value LS_LINK_TYPE (.+?)
Value LS_LINK_ID (\d+\.\d+\.\d+\.\d+)
Value LS_LINK_DATA (\d+\.\d+\.\d+\.\d+)
Value LS_MTID_METRICS (\d+)
Value LS_TOS_0_METRICS (\d+)

Start
  ^\s+OSPF\s+Router\s+with\s+ID\s+\(${ROUTER_ID}\)\s+\(Process\s+ID\s+${PROCESS_ID}\)
  ^\s+Router\s+Link\s+States\s+\(Area ${AREA}\) -> LSAInfo
  ^\s*$$
  ^. -> Error

LSAInfo
  ^\s+LS\s+age:\s+${LSA_AGE}
  ^\s+Options:\s+\(${LSA_OPTIONS}\)
  ^\s+LS\s+Type:\s+${LSA_TYPE}
  ^\s+Link\s+State\s+ID:\s+${LSA_ID}
  ^\s+Advertising\s+Router:\s+${LSA_ADV_ROUTER}
  ^\s+LS\s+Seq\s+Number:\s+${LSA_SEQ_NUMBER}
  ^\s+Checksum:\s+${LSA_CHECKSUM}
  ^\s+Length:\s+${LSA_LENGTH}
  ^\s+Number\s+of\s+Links:\s+${LSA_NUM_LINKS} -> LSAs
  ^\s*$$
  ^. -> Error

LSAs
  ^\s+Link\s+connected\s+to:\s+${LS_LINK_TYPE}$$
  ^\s+\(Link ID\)\s+((Network\/subnet\s+number)|(Designated\s+Router\s+address)|(Neighboring\s+Router ID)):\s+${LS_LINK_ID}
  ^\s+\(Link Data\)\s+((Network\s+Mask)|(Router\s+Interface\s+address)):\s+${LS_LINK_DATA}
  ^\s+Number\s+of\s+MTID\s+metrics:\s+${LS_MTID_METRICS}
  ^\s+TOS\s+0\s+Metrics:\s+${LS_TOS_0_METRICS} -> Next.Record
  ^\s+LS\s+age:\s+${LSA_AGE} -> LSAInfo
  ^\s*$$
  ^. -> Error

EOF
```

##### SAMPLE COMMAND OUTPUT

The observed output via the CLI is misleading, as illustrated below, using Netmiko to get the output of ```show ip ospf database router```

```python
import netmiko

deviceDict = {
    "host": "10.10.10.10",
    "username": "cisco",
    "password": "cisco",
    "device_type": "cisco_ios",
}
connection = netmiko.ConnectHandler(**deviceDict)
db = connection.send_command("show ip ospf database router")

# Print the first 100 characters of the output to illustrate the actual output
print(db[0:100])
```

The above code snippet will result in the output that follows.  Note that the first character of the output is a non-space character.

```
OSPF Router with ID (10.10.10.10) (Process ID 1)

                Router Link States (Area 10.10.10.10)

  LS age:
```

##### SUMMARY

**Note:**  This same behavior is observed when using both the ```show ip ospf database router``` and ```show ip ospf database network``` templates, and for the same reason in both cases.

The template is expecting output similar to that which is observed when the actual ```show ip ospf database router``` command is entered via the CLI.  The reality is that the leading spaces are truncated prior to being parsed by the template.

To be specific, the first regex in the ```Start``` state should match _zero or more_ space characters, but instead will match _one or more_ space characters.

I would suggest changing lines 20 and 16 in ```cisco_ios_show_ip_ospf_database_router.textfsm``` and ```cisco_ios_show_ip_ospf_database_network.textfsm```, respectively, as follows:

```diff
-   ^\s+OSPF\s+Router\s+with\s+ID\s+\(${ROUTER_ID}\)\s+\(Process\s+ID\s+${PROCESS_ID}\)
+   ^\s*OSPF\s+Router\s+with\s+ID\s+\(${ROUTER_ID}\)\s+\(Process\s+ID\s+${PROCESS_ID}\)
```

I can submit a pull request, but wanted to make sure the problem was documented first.

##### STEPS TO REPRODUCE

Use Netmiko to get the output of ```show ip ospf database router``` using ntc-templates with TextFSM parsing.

```python
import netmiko

deviceDict = {
    "host": "10.10.10.10",
    "username": "cisco",
    "password": "cisco",
    "device_type": "cisco_ios",
}
connection = netmiko.ConnectHandler(**deviceDict)
db = connection.send_command("show ip ospf database router", use_textfsm=True)
```

##### EXPECTED RESULTS

In this context, I would not expect an error.

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/base_connection.py", line 1447, in send_command
    template=textfsm_template,
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 280, in get_structured_data
    return _textfsm_parse(textfsm_obj, raw_output, attrs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/utilities.py", line 252, in _textfsm_parse
    textfsm_obj.ParseCmd(raw_output, attrs)
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 272, in ParseCmd
    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])
  File "/home/me/.venv/lib64/python3.6/site-packages/netmiko/_textfsm/_clitable.py", line 303, in _ParseCmdItem
    for record in fsm.ParseText(cmd_input):
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 895, in ParseText
    self._CheckLine(line)
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 944, in _CheckLine
    if self._Operations(rule, line):
  File "/home/me/.venv/lib64/python3.6/site-packages/textfsm/parser.py", line 1025, in _Operations
    % (rule.line_num, line))
textfsm.parser.TextFSMError: State Error raised. Rule Line: 23. Input Line: OSPF Router with ID (10.10.10.10) (Process ID 1)
```

**Comment by FragmentedPacket** [comment]
Sounds good. Looking forward to your PR!

**Comment by ariesgeek** [comment]
> Sounds good. Looking forward to your PR!
> 
> Make sure to add your output as an additional test as well.

Done and done, Pull Request: #650 

Thank you!
